const chatData = [
  {
    id: 1,
    businessName: "Plush Beauty Lounge",
    message: "Good morning, anything we ca...",
    time: "11:32 PM",
    unreadCount: 6,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
  },
  {
    id: 2,
    businessName: "Plush Beauty Lounge",
    message: "Good morning, anything we ca...",
    time: "11:32 PM",
    unreadCount: 2,
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2",
  },
  {
    id: 3,
    businessName: "Plush Beauty Lounge",
    message: "Good morning, anything we ca...",
    time: "11:32 PM",
    unreadCount: 2,
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
  },
  {
    id: 4,
    businessName: "Cute Stuff Salon",
    message: "I would like to book an appoin...",
    time: "Yesterday",
    unreadCount: 4,
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f",
  },
  {
    id: 5,
    businessName: "Cute Stuff Salon",
    message: "I would like to book an appoin...",
    time: "Yesterday",
    unreadCount: 0,
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
  },
  {
    id: 6,
    businessName: "Cute Stuff Salon",
    message: "I would like to book an appoin...",
    time: "Yesterday",
    unreadCount: 0,
    avatar: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e",
  },
  {
    id: 7,
    businessName: "Elegant Nails Studio",
    message: "Your appointment is confirmed...",
    time: "Yesterday",
    unreadCount: 0,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
  },
  {
    id: 8,
    businessName: "Urban Barber Shop",
    message: "We have a special offer this...",
    time: "Yesterday",
    unreadCount: 0,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
  },
  {
    id: 9,
    businessName: "Serene Spa Retreat",
    message: "Thank you for your visit! We...",
    time: "2 days ago",
    unreadCount: 0,
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7",
  },
  {
    id: 10,
    businessName: "Glamour Hair Salon",
    message: "Reminder: Your hair treatment...",
    time: "1 week ago",
    unreadCount: 0,
    avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df",
  },
  {
    id: 11,
    businessName: "Modern Wellness Center",
    message: "New services now available!...",
    time: "2 week ago",
    unreadCount: 0,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2",
  },
];
export default chatData;
